
- hosts: all
  become: yes
  tasks:

    # --------------------
    # Cleanup old repos
    # --------------------
    - name: Remove old Docker repo definitions if they exist
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/docker.list
        - /etc/apt/sources.list.d/download_docker_com_linux_ubuntu.list

    - name: Remove old Jenkins repo definitions if they exist
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/jenkins.list
        - /etc/apt/sources.list.d/pkg_jenkins_io_debian.list
        - /etc/apt/sources.list.d/jenkins.sources
        - /usr/share/keyrings/jenkins-keyring.gpg
        - /usr/share/keyrings/jenkins-keyring.asc

    # --------------------
    # Update packages
    # --------------------
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    # --------------------
    # Docker installation
    # --------------------
    - name: Add Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Add Docker repo
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu noble stable"
        state: present
        filename: docker

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    # --------------------
    # Java installation
    # --------------------
    - name: Install Java 17
      apt:
        name: openjdk-17-jdk
        state: present

    # --------------------
    # Jenkins installation
    # --------------------
    - name: Add Jenkins GPG key
      get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.gpg
        mode: '0644'

    - name: Add Jenkins repo
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.gpg] https://pkg.jenkins.io/debian binary/"
        state: present
        filename: jenkins

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Enable Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes

    
